build:
  nodes:
    analysis:
      environment: { php: 8.2 }
      dependencies:
        override:
          - wget -q https://phar.phpunit.de/phpunit-9.6.phar -O phpunit.phar
      tests:
        override:
          - command: "php phpunit.phar --configuration phpunit.xml.dist --coverage-clover=coverage.xml"
            coverage:
              file: coverage.xml
              format: php-clover
filter:
  excluded_paths:
    - tests/*
    - proj/*
    - vendor/*
    - public/*
checks:
  php: true
tools:
  external_code_coverage: false
